### ISSUE TITLE
Uncaught TypeError: APIS.tetPost is not a function

### ISSUE THREAD

**Issue by leonhu0710** [swlws/vue3-monorepo-temp#1]
runtime-core.esm-bundler.js:218 Uncaught TypeError: APIS.tetPost is not a function
    at testPost (test.ts:36:8)
    at doPostTest (index.vue:34:3)

**Comment by swlws** [comment]
just spelling errors, alreay fix
"APIS.tetPost" --> "APIS.testPost"
